[package]
name = "rmatrix"
version = "0.1.0"
authors = ["Richard Menzies <rdmenzies2000@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
rand = "0.7.3"
